[logs]
level = "info" # Options: "error", "warn", "info", "debug", "trace"
enable_reqwest_logging = false

[media]
use_original_title = true # deprecated by title_strategy, kept for backward compatibility
enable_mediainfo_cache = true
seed_path = "/mnt/nas/medias/plex/library/.seedarr"
append_no_tag_on_missing_group = true
title_strategy = "original_if_en_else_local" # or "always_local"

[torrent]
announce_url = "https://tracker.bartho.dev/announce/N4iuXcA29S7wmg07yXsa5vQYRWiyAl0n"
private = true
output_dir = "/mnt/nas/torrents/.seedarr"
dry_run = true

[[radarr.path_mappings]]
radarr_root = "/data/library/movies"
local_root = "/mnt/nas/medias/plex/library/movies"

# [[radarr.path_mappings]]
# radarr_root = "/data/library/animation"
# local_root = "/mnt/nas/medias/plex/library/animation"

# [[radarr.path_mappings]]
# radarr_root = "/data/library/documentaries"
# local_root = "/mnt/nas/medias/plex/library/documentaries"
